=== Bobr2004/JavaLab2/target/classes/xsd/beer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Перелічуваний тип для Type -->
    <xs:simpleType name="BeerType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="темне"/>
            <xs:enumeration value="світле"/>
            <xs:enumeration value="лагерне"/>
            <xs:enumeration value="живе"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Перелічуваний тип для Al -->
    <xs:simpleType name="AlcoholType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="алкогольне"/>
            <xs:enumeration value="безалкогольне"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Граничні значення для обертів та прозорості -->
    <xs:simpleType name="PercentageType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Основний елемент Beer -->
    <xs:element name="Beer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="beerItem" maxOccurs="unbounded"> <!-- renamed from "beer" -->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredients">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingredient" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="chars">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="abv" type="xs:decimal" minOccurs="0"/>
                                        <xs:element name="transparency" type="PercentageType"/>
                                        <xs:element name="filtered" type="xs:string"/>
                                        <xs:element name="nutritionalValue" type="xs:int"/>
                                        <xs:element name="packaging">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="volume" type="xs:decimal"/>
                                                    <xs:element name="material" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="type" type="BeerType" use="required"/>
                        <xs:attribute name="al" type="AlcoholType" use="required"/>
                        <xs:attribute name="manufacturer" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== Bobr2004/JavaLab2/src/main/resources/beer.xml
<?xml version="1.0" encoding="UTF-8"?>
<Beer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/beer.xsd">
    <beerItem id="1" name="Stout" type="темне" al="алкогольне" manufacturer="Brewery A">
        <ingredients>
            <ingredient>Water</ingredient>
            <ingredient>Barley</ingredient>
            <ingredient>Hops</ingredient>
            <ingredient>Yeast</ingredient>
        </ingredients>
        <chars>
            <abv>6.5</abv>
            <transparency>20</transparency>
            <filtered>Yes</filtered>
            <nutritionalValue>150</nutritionalValue>
            <packaging>
                <volume>0.5</volume>
                <material>Glass</material>
            </packaging>
        </chars>
    </beerItem>
    <beerItem id="2" name="Lager" type="світле" al="алкогольне" manufacturer="Brewery B">
        <ingredients>
            <ingredient>Water</ingredient>
            <ingredient>Rice</ingredient>
            <ingredient>Hops</ingredient>
            <ingredient>Yeast</ingredient>
        </ingredients>
        <chars>
            <abv>5.0</abv>
            <transparency>70</transparency>
            <filtered>No</filtered>
            <nutritionalValue>130</nutritionalValue>
            <packaging>
                <volume>0.33</volume>
                <material>Can</material>
            </packaging>
        </chars>
    </beerItem>
    <beerItem id="3" name="Non-Alcoholic Wheat" type="живе" al="безалкогольне" manufacturer="Brewery C">
        <ingredients>
            <ingredient>Water</ingredient>
            <ingredient>Wheat</ingredient>
            <ingredient>Hops</ingredient>
            <ingredient>Yeast</ingredient>
        </ingredients>
        <chars>
            <abv>0.0</abv>
            <transparency>60</transparency>
            <filtered>Yes</filtered>
            <nutritionalValue>90</nutritionalValue>
            <packaging>
                <volume>0.5</volume>
                <material>Plastic</material>
            </packaging>
        </chars>
    </beerItem>
</Beer>
